### ISSUE TITLE
Models & Code for trained detection methods   

### ISSUE THREAD

**Issue by khaghanijavad** [tum-fml/loco#4]
Hi, 
Thank you very much for your interesting work and for publicly releasing your dataset. 
Do you have any plans to release the checkpoints of trained Yolo-V4 & Fater-RCNN detection methods? 

Thanks

**Comment by Belidan** [comment]
Greetings,
you can find a repository for YOLO-V5 trained with LOCO here: https://github.com/mayershoc/loco_yolov5.
We will check if we are able to release the checkpoints for V4 and Faster-RCNN.

Kind regards,
Dimitrij

**Comment by khaghanijavad** [comment]
Thank you very much for the reply.
Sincerely,
Javad
