### ISSUE TITLE
Access to files on MWN unrelated to the dataset

### ISSUE THREAD

**Issue by KoniHD** [tum-fml/loco#9]
Since I was interested in the dataset I naturally explored the annotated and additional data that can be reached by the provided links in the `README.md`. However, as exploring the additional data provided by the link [http://go.mytum.de/928009](url) I realized one can open more directories than probably anticipated. In short by going up the directory path one can reach a directory called `Studien` containing files like `Kennzahlensysteme_in_der_Automobillogistik.pdf`. I am not providing the download link here as I am unsure whether this was intended but I wanted to raise awareness as it doesn't seem related to the LOCO dataset.

**Comment by frothm** [comment]
Hi, Many thanks for raising awareness about the accessability of other files on our NAS! In the mentioned folder structure, we gather all the resources we have published in various channels, so the access configuration is actually intended. Nevertheless, we double-checked the access rights and didn't find any unintended hole.
Best regards, Florian
